# tasks file
---
- name: generate (backup) script
  template:
    src: usr/local/bin/mydumper-backup.j2
    dest: "{{ mydumper_backup_install_path }}/mydumper-backup"
    owner: root
    group: root
    mode: 0750
    validate: '/usr/bin/env bash -n %s'
  tags:
    - configuration
    - mydumper-backup
    - mydumper-backup-configuration

- name: generate (restore) script
  template:
    src: usr/local/bin/mydumper-restore.j2
    dest: "{{ mydumper_backup_install_path }}/mydumper-restore"
    owner: root
    group: root
    mode: 0750
    validate: '/usr/bin/env bash -n %s'
  tags:
    - configuration
    - mydumper-backup
    - mydumper-backup-configuration
